laravel/app/Http/Controllers/Api/ComboController.php
laravel/app/Service/ComboService.php

make combo api

---

laravel/app/Facades/CharacterService.php
laravel/app/Http/Controllers/Api/CharacterController.php
laravel/app/Providers/CharacterServiceProvider.php
laravel/app/Service/CharacterService.php
laravel/config/app.php
laravel/routes/api.php
laravel/tests/Feature/Api/CharacterControllerTest.php
laravel/tests/Unit/Service/CharacterServiceTest.php

make character api

---

laravel/resources/assets/js/components/views/combo/comboList.vue
laravel/resources/assets/js/components/views/games.vue

ゲーム選択画面で選択したゲームのIDをローカルストレージに追加しています。
コンボ一覧画面で現在選択しているゲームのタイトルを表示。
コンボ一覧画面で選択しているゲームのキャラクターを取得する。

game id regist localstorage

---

laravel/resources/assets/js/components/views/setting/address.vue

 #46 make settig mailAddress parts

---

laravel/resources/assets/js/components/views/setting/password.vue

 #47 make setting password parts

---

laravel/resources/assets/js/components/views/setting/deleteId.vue

 #50 make setting delete id parts

---

laravel/app/Model/Combo.php
laravel/app/Service/ComboService.php

コンボに紐付いたキャラクター、レシピの1番目を返すようにしました

make combo index

---

laravel/.gitignore
laravel/_ide_helper.php
laravel/_ide_helper_models.php
laravel/app/Facades/UserService.php
laravel/app/Http/Controllers/Api/UserController.php
laravel/app/Http/Requests/UserStore.php
laravel/app/Model/User.php
laravel/app/Providers/AppServiceProvider.php
laravel/app/Providers/UserServiceProvider.php
laravel/app/Service/UserService.php
laravel/composer.json
laravel/composer.lock
laravel/config/app.php
laravel/database/migrations/2017_07_01_123300_delete_name_to_users_table.php
laravel/database/seeds/UsersTableSeeder.php
laravel/routes/api.php

Userに関係ないやつはIDEヘルパーです。
Laravelで利用しているファサードはそのままでは静的解析できないので
ヘルパーを入れることによって有効にします。

add user regist api & add IDE helper

---

laravel/resources/assets/js/components/views/combo/comboList.vue
laravel/routes/api.php

現在、絞り込みモーダルの技はモックAPIから取得した技を表示している
モックAPIではなく、選択したキャラの技を表示させる
#70

#70 絞り込みモーダルで選択したキャラの技を表示させる

---

laravel/app/Http/Controllers/Api/ComboController.php
laravel/app/Model/Recipe.php
laravel/app/Service/ComboService.php

コンボレシピに技情報を付与
始動技、終了技のみでなく、コンボ中のレシピを全て返却するように修正
コンボの情報を返すAPIなので、始動技、終了技など意識するのは利用側で
返す側は全て返すようにすれば良いため
パフォーマンスとか問題出てきたらまた考える

add move detail

---

laravel/resources/views/app.blade.php
laravel/webpack.mix.js

バージョンをつけることによってキャッシュに残って古いソースにならないようにしました

アセットのバージョン付

---

laravel/resources/assets/js/components/views/combo/comboDetail.vue

#97 コンボ詳細画面に消費ゲージを表示する

---

laravel/resources/assets/js/components/views/combo/comboDetail.vue

#99 コンボ詳細画面にコンボレシピを表示する

---

laravel/resources/assets/js/components/views/combo/comboList.vue

#74 コンボ一覧に始動技を表示

---

laravel/resources/assets/js/components/views/combo/comboList.vue

#75 コンボ一覧画面に終了技を表示させる

---

laravel/app/Http/Controllers/Api/AuthController.php
laravel/app/Http/Controllers/Api/UserController.php
laravel/resources/assets/js/components/views/top.vue
laravel/routes/api.php
laravel/tests/Feature/Api/AuthControllerTest.php

ユーザー登録機能の実装
https://github.com/full-party/CrossUp/pull/106
上記プルリクエストのブランチをマージしているので上記プルリクエストからレビューをお願いします。
#87

#87 ユーザー登録機能の実装

---

laravel/app/Http/Controllers/Api/AuthController.php
laravel/app/Http/Controllers/Api/UserController.php
laravel/routes/api.php
laravel/tests/Feature/Api/AuthControllerTest.php

UserControllerのログインと登録をAuthControllerに移動
ログインをPOSTに変更
#104

#104 ログイン、登録処理のリファクタリング

---

laravel/app/Http/Controllers/Api/AuthController.php
laravel/app/Http/Controllers/Api/UserController.php
laravel/resources/assets/js/components/views/top.vue
laravel/routes/api.php
laravel/tests/Feature/Api/AuthControllerTest.php

トップでログインAPIを利用しログイン機能を実装
https://github.com/full-party/CrossUp/pull/105
上記プルリクエストのブランチをマージして実装しているので
上記プルリクエストからレビューよろしくお願いします
#103

#103 ログインAPIの利用

---

laravel/app/Http/Controllers/Controller.php
laravel/app/Http/Kernel.php
laravel/app/Http/Middleware/CheckLogin.php
laravel/routes/web.php

ログインしてない場合TOPにリダイレクトさせる
下記ポイントレビューお願いします。
既存のコントローラにやらせているが問題ないか？
チェックの仕方は問題ないか？
#95

#95 ログインしてない場合TOPにリダイレクトさせる

---

laravel/app/Service/ComboService.php
laravel/config/sort.php
laravel/resources/assets/js/components/views/combo/comboList.vue
laravel/routes/api.php

ソートAPIの作成、利用
作った代わりに絞り込みがこのままではバグですが、違うIssueで修正します。
#84

#84 ソートAPIの作成、利用

---

laravel/app/Http/Controllers/Api/AuthController.php
laravel/resources/assets/js/components/common/app-sidebar.vue
laravel/routes/api.php

ログアウトAPI、APIの利用
レビュー観点
APIはセッション破棄でいいのか？
返り値なしでいいのか？
#114

#114 ログアウトAPI、APIの利用

---

laravel/Procfile

add Procfile

---

resources/assets/js/components/views/setting/deleteId.vue

ブランチ作成時はデプロイされないこと
PR承認時はデプロイされることをテスト

プルリクエストの自動デプロイテスト

---

resources/assets/js/app.js
resources/assets/js/components/common/app-header.vue
resources/assets/js/router.js
resources/views/app.blade.php

トップでヘッダーを消す
https://router.vuejs.org/ja/essentials/named-views.html
vue-routerの公式を真似しました
#123

#123 トップでヘッダーを消す

---

app/Model/Combo.php
app/Service/ComboService.php
resources/assets/js/components/views/combo/comboList.vue

絞り込みAPIの実装
DBから取得後に始動技のフィルタをしているが、DB取得時に絞り込みができるのか調べたが不明だった。
#85

#85 絞り込みAPIの実装

---

app/Http/Controllers/Api/ComboController.php
app/Service/ComboService.php
resources/assets/js/components/views/combo/comboDetail.vue

コンボ削除APIの作成、利用
DB処理弱いので、削除ロジック問題ないかレビューお願いします
#83

#83 コンボ削除APIの作成、利用

---

.travis.yml
README.md
database/seeds/CharactersTableSeeder.php
database/seeds/CombosTableSeeder.php
database/seeds/DatabaseSeeder.php
database/seeds/GamesTableSeeder.php
database/seeds/MovesTableSeeder.php
database/seeds/RecipesTableSeeder.php
database/seeds/TestDatabaseSeeder.php
database/seeds/UsersTableSeeder.php

#130 
テストシーダーとマスターシーダーに分割しました
どちらも冪等性を担保しているので、何度実行してもテーブルの状態が同じ結果になります。
本番ではマスターが更新されるたびにマスターシーダーを実行する感じです

split testSeeder from masterSeeder

---

app/Http/Controllers/Api/UserController.php
app/Http/Requests/UserUpdate.php
app/Model/User.php
tests/Feature/Api/UserControllerTest.php

#52 ログインID変更API

---

app/Model/ComboStatus.php
app/Model/Status.php
database/migrations/2017_11_03_162413_create_statuses_table.php
database/migrations/2017_11_03_162415_create_combo_statuses_table.php
database/migrations/2017_11_03_163433_add_foreign_keys_to_statuses_table.php
database/migrations/2017_11_03_163444_add_foreign_keys_to_combo_statuses_table.php
database/seeds/ComboStatusTableSeeder.php
database/seeds/DatabaseSeeder.php
database/seeds/StatusTableSeeder.php
database/seeds/TestDatabaseSeeder.php

コンボステータスマイグレーション作成

---

app/Model/Combo.php
app/Model/ComboStatus.php
app/Model/Recipe.php
app/Service/ComboService.php
tests/Feature/Api/ComboControllerTest.php

マイグレーションマージ後に確認してください。
あまりにも簡単に追加が行けてしまったのでびっくり。
ついでにfillでコンボとレシピの登録リファクタリングしてみた。
かなり行数が減った！

コンボ登録API - ステータス登録追加

---

app/Service/ComboService.php
tests/Feature/Api/ComboControllerTest.php

コンボ詳細APIの戻り値にステータスを追加する
レシピと同じリレーションなので
レシピと同じくwithキーワードに追加する実装

#147 Add ComboStatus to ComboShowApi

---

package-lock.json
package.json
resources/assets/js/actions.js
resources/assets/js/app.js
resources/assets/js/components/views/combo/comboCreate.vue
resources/assets/js/components/views/combo/comboList.vue
resources/assets/js/components/views/games.vue
resources/assets/js/mutations.js
resources/assets/js/store.js

https://vuex.vuejs.org/ja/intro.html
コンポーネント間の情報の受け渡し、共有が辛くなりそう
例：gameId、user情報（今後）
また、キャラクターやソート情報は毎回APIで取る必要はないと考えているのでstateにいれたいため
- vuexのinstall
- ゲーム選択コンポーネントでgame情報をstateに追加
- 各コンポーネントはstateからgame情報を取得
- 初期ローディング時にLSにあったらstateに追加
- WFデザインにゲームタイトルはなかったので一旦削除
#125

#125 vuex 導入

---

resources/assets/js/components/views/combo/comboCreate.vue

キャラクター選択モーダルはいじってません
WFの通りに実装しました
#156

#156 【デザイン実装】【SP】【コンボ入力画面】コンボ入力実装 

---

app/Facades/Combos/StatusService.php
app/Http/Controllers/Api/Combos/StatusController.php
app/Http/Requests/Combos/StatusIndex.php
app/Providers/Combos/StatusServiceProvider.php
app/Service/Combos/StatusService.php
config/app.php
routes/api.php

コンボ登録画面で、コンボステータス選択用のセレクトボックス作成のため
ここを参考に設計してみた
http://tech.connehito.com/entry/2017/06/02/111133
/combos/statuses

コンボステータス一覧取得API作成

---

app/Http/Controllers/Api/ComboController.php
app/Http/Requests/ComboStore.php
resources/assets/js/components/common/combo-input.vue
resources/assets/js/components/views/combo/comboCreate.vue
resources/assets/js/components/views/combo/comboEdit.vue
tests/Feature/Api/ComboControllerTest.php

コンボ編集画面のデザイン実装
コンボ入力画面とほぼ同じなので、コンポーネント化しました。
form部分をまるっとコンポーネント化して、2つの画面で利用できるように修正しました。
また、postパラメーター修正しました。
#165 
#36

#165 【デザイン実装】【SP】【コンボ編集画面】コンボ編集実装 

---

database/seeds/data/character.csv
resources/assets/js/components/common/combo-input.vue
resources/assets/js/components/common/modal.vue

コンボ登録画面でキャラクター選択時に画像を表示させました
また、カリンの画像パスが違ったので修正しました。
#192

#192 コンボ登録画面でキャラクター選択時に画像を表示させる

---

resources/assets/js/components/common/combo-cassette.vue

コンボ一覧でコンボカセットにキャラの画像を表示させる
#195

#194 コンボ一覧でコンボカセットにキャラの画像を表示させる

---

resources/assets/js/components/views/combo/comboDetail.vue

#198 コンボ詳細画面でキャラクター画像を表示する

---

resources/assets/js/components/views/setting/setting.vue

#177 設定画面のデザイン実装

---

app/Http/Controllers/Api/UserController.php
app/Model/User.php
app/Service/UserService.php
routes/api.php
tests/Feature/Api/UserControllerTest.php

ユーザー削除API作成

---

resources/assets/js/components/views/setting/id.vue

#178 ID設定画面のデザイン実装

---

resources/assets/js/components/views/setting/address.vue

#179 メールアドレス変更画面のデザイン実装

---

resources/assets/js/components/views/combo/comboDetail.vue

ついでにmeterは日本だとゲージと呼ばれるので変更しました

コンボ詳細画面、ステータス追加

---

resources/assets/js/components/views/setting/password.vue

#180 パスワード変更画面のデザイン実装

---

resources/assets/js/components/views/setting/deleteId.vue

#181 退会画面のデザイン実装

---

resources/assets/js/components/common/box/move-accordion-box.vue
resources/assets/js/components/views/combo/comboList.vue

#219 始動技絞り込みのデザイン実装

---

resources/assets/js/components/common/box/sort-accordion-box.vue
resources/assets/js/components/views/combo/comboList.vue

#220 絞り込みの並び順のデザイン実装

---

resources/assets/js/components/views/top.vue

#171 PCのトップデザイン実装

---

resources/assets/js/components/views/combo/comboDetail.vue

#173 PCのコンボ詳細デザイン実装

---

resources/assets/js/components/common/combo-input.vue
resources/assets/js/components/views/combo/comboCreate.vue

PCのコンボ入力画面のデザイン実装
くっつけただけ
デリバリー優先で・・・嘆き
#175

#175 【デザイン実装】【PC】【コンボ入力】
